app2/config/routes.rb
Rails.application.routes.draw do
get '/login', to: 'access#new'
  get 'access/new'
  get 'access/create'
  get 'access/destroy'
  get 'admin/index'
  resources :users
  resources :orders
  resources :lineitems
  resources :carts
  get 'shopper/index'
  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "shopper#index", as: 'root'
 get '/shopper', to: 'shopper#index'
 get '/admin', to: 'admin#index'
 post '/admin', to: 'admin#index'
 post '/admin/index', to: 'admin#index'
 post '/login', to: 'admin#index'

end

app2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 <title>Store</title>
 <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body class='<%= controller.controller_name %>'>
 <div id="banner">
 <%= image_tag("logo.png") %>
 <%= @page_title || "Our Products" %>
 <%= button_to 'Admin', products_path, method: :get  %>
 </div>
 <div id="columns">
 <div id="side">
 	<%if controller_name == "orders" || controller_name=="shopper"%>
 	<div id='cart'>
		<%=render @cart %> 

	</div>
	<%end%>
 <!--<ul>
 <li><a href="http://www....">Home</a></li>
 <li><a href="http://www..../faq">Questions</a></li>
 <li><a href="http://www..../news">News</a></li>
 <li><a href="http://www..../contact">Contact</a></li>
 </ul>-->

 <% if session[:user_id] %>
    <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
    <%= button_to 'Logout', logout_path, method: :delete   %>
<% end %>

 </div>
 <div id="main">
 <%= yield %>
 </div>
 </div>
</body>
</html> 